# Generated by Django 6.0.7 on 2026-07-14 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPlanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('study', 'Study'), ('break', 'Break'), ('revision', 'Revision')], default='study', max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Why the AI engine chose this slot', max_length=255)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_slots', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_available_hours', models.DecimalField(decimal_places=1, default=6.0, max_digits=4)),
                ('preferred_start_time', models.TimeField(default='09:00')),
                ('break_duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('long_session_minutes', models.PositiveSmallIntegerField(default=90, help_text='Minutes of focused study before a break is inserted')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
